### PR TITLE
31 service sector code translation will return additional column

### PR DESCRIPTION
**Pull request by shanmukhasampath**
This is for issue #31 

- [x] TESTED IT OUT
- [x] NO LONGER MISSES UNMAPPED SERVICE SECTOR CODES

### CODE REVIEW

**Comment by javier-gracia-tabuenca-tuni** [comment]
We need some discussion, i make notes here 
- Can we just list the finngen codes we want to flag, instead of the omop, hence not needing the concept and relationship tables ?
- if not, we can pass as parameter only the schema to cdm, not both path to concept and path to relationship tables. But preferably none, if we can do as in point one

**Comment by shanmukhasampath** [comment]
Hi Javier, 

- Can we just list the finngen codes we want to flag, instead of the omop, hence not needing the concept and relationship tables?

 Yes, this can be done but it would too many codes to consider and we will have to keep updating these codes in the future if we have any update to the OMOP map. This would be difficult to manage. I would suggest us not to go this way

- if not, we can pass as parameter only the schema to cdm, not both path to concept and path to relationship tables. But preferably none, if we can do as in point one

 This is something I wanted to talk to about. Yes, we can utilize the cdm schema to do this task so that there is no need for concept and concept_relationship parameters within the function. This would work.

**Comment by javier-gracia-tabuenca-tuni** [comment]
(making notes here, do not act, you are on holidays!!!)
This is breaking the unit tests 
- It is making returning all the visit_tipe_code as the same  "fg_bq_append_visit_type_info_to_service_sector_data works"
image
(up expected, down return)
- It is removing some lines "fg_bq_append_visit_type_info_to_service_sector_data overlap hilmo code5 CODE98"

**Comment by javier-gracia-tabuenca-tuni** [comment]
Tmp notes, they may be wrong
I think error 1 is bcs line 71 on append_cisit_type_info_to_service_sector.sql is setting FG_CODES to null if there is nor mapping. ( may be should be NOT NULL)
I think error 2 is bcs line 170
-- remove hilmo inpat visits that are inpatient with ndays=1 or ourtpatient with ndays>1
We shouldnt remove anything, this fuctions only add columns to the input table, never remove anything from the input table

**Comment by javier-gracia-tabuenca-tuni** [comment]
done by #38

**Pull request closed without merging**
